In [1]:
import numpy as np

In [2]:
n = int(input("nhập số đỉnh: "))
m = int(input("nhập số cạnh: "))

admatrix = np.array([[0 for i in range(n+1)] for j in range(n+1)])
admatrix[0] = [i for i in range(n+1)]
for i in range(n+1):
    admatrix[i][0] = i

for i in range(m):
    u = int(input("nhập u: "))
    v = int(input("nhập v: "))
    admatrix[u][v] = 1
    admatrix[v][u] = 1

print(admatrix)

[[ 0  1  2  3  4  5  6  7  8  9 10]
 [ 1  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  0]
 [ 3  0  0  0  0  0  0  0  0  0  0]
 [ 4  0  0  0  0  0  0  0  0  0  0]
 [ 5  0  0  0  0  0  0  0  0  0  0]
 [ 6  0  0  0  0  0  0  0  0  0  0]
 [ 7  0  0  0  0  0  0  0  0  0  0]
 [ 8  0  0  0  0  0  0  0  0  0  0]
 [ 9  0  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0  0]]
